### ISSUE TITLE
Bug in Python scripts

### ISSUE THREAD

**Issue by albertz** [openlierox/openlierox#163]
Converted from [SourceForge issue 2578110](http://sourceforge.net/support/tracker.php?aid=2578110), submitted by dark_charlie

Today I was running the dedicated server. After few hours it stopped responding to any commands and it didn't start either. Here are the outputs:
Traceback (most recent call last):
  File "C:\Users\Karel Petránek\Documents/OpenLieroX/scripts/dedicated_control", line 41, in <module>
    while hnd.signalHandler(io.getSignal()):
  File "c:\Users\Karel Petránek\Documents\Programovani\OpenLieroX\share\gamedir\scripts\dedicated_control_handler.py", line 120, in signalHandler
    parseWormLeft(sig)
  File "c:\Users\Karel Petránek\Documents\Programovani\OpenLieroX\share\gamedir\scripts\dedicated_control_handler.py", line 239, in parseWormLeft
    cmds.recheckVote()
  File "c:\Users\Karel Petránek\Documents\Programovani\OpenLieroX\share\gamedir\scripts\dedicated_control_usercommands.py", line 233, in recheckVote
    if hnd.worms[votePoster].Voted == 1: # Check if worm left and another worm joined with same ID
KeyError: 0

2009-02-07 15:24:52 -- INFO -- Dedicated_control started
2009-02-07 15:25:34 -- INFO -- Python still alive
(...)
2009-02-07 16:30:23 -- INFO -- Python still alive
2009-02-07 16:42:45 -- INFO -- Dedicated_control started
2009-02-07 16:43:27 -- INFO -- Python still alive
2009-02-07 16:57:21 -- INFO -- Dedicated_control started
2009-02-07 16:58:02 -- INFO -- Python still alive
(...)
2009-02-07 17:12:50 -- INFO -- Python still alive
2009-02-07 17:31:23 -- INFO -- Dedicated_control started
(...)
2009-02-07 17:44:54 -- INFO -- Python still alive
2009-02-07 17:45:33 -- USERCOMMAND -- 4:Bomb issued preset
2009-02-07 17:45:34 -- INFO -- Python still alive
2009-02-07 17:45:37 -- USERCOMMAND -- 4:Bomb issued y
2009-02-07 17:45:40 -- USERCOMMAND -- 4:Bomb issued y
2009-02-07 17:45:48 -- USERCOMMAND -- 0:Cee Dee issued y
2009-02-07 17:46:00 -- USERCOMMAND -- 4:Bomb issued preset
2009-02-07 17:46:14 -- INFO -- Python still alive
2009-02-07 17:46:15 -- USERCOMMAND -- 4:Bomb issued kick
2009-02-07 17:46:15 -- ERROR -- ('ValueError', '<no args>', ['  File "c:\Users\Karel Petr\xe1nek\Documents\Programovani\OpenLieroX\share\gamedir\scripts\dedicated_control_usercommands.py", line 285, in parseUserCommand\n    kicked = int( params[0] )\n'])
(...)
2009-02-07 18:11:20 -- USERCOMMAND -- 1:Cee Dee issued preset
(...)
2009-02-07 18:17:38 -- USERCOMMAND -- 1:Cee Dee issued preset
(...)
2009-02-07 18:31:59 -- USERCOMMAND -- 1:Cee Dee issued preset
2009-02-07 18:32:02 -- USERCOMMAND -- 1:Cee Dee issued y
(...)
2009-02-07 18:45:01 -- USERCOMMAND -- 1:PoLeQ issued !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2009-02-07 18:45:01 -- ERROR -- ('Exception', '<no args>', ['  File "c:\Users\Karel Petr\xe1nek\Documents\Programovani\OpenLieroX\share\gamedir\scripts\dedicated_control_usercommands.py", line 339, in parseUserCommand\n    raise Exception, "Invalid user command"\n'])
2009-02-07 18:45:39 -- INFO -- Python still alive
2009-02-07 18:46:16 -- USERCOMMAND -- 2:Bomb issued preset
2009-02-07 18:46:19 -- INFO -- Python still alive
2009-02-07 18:46:25 -- USERCOMMAND -- 2:Bomb issued preset
2009-02-07 18:46:28 -- USERCOMMAND -- 2:Bomb issued y
2009-02-07 18:46:31 -- USERCOMMAND -- 2:Bomb issued y
2009-02-07 18:46:35 -- USERCOMMAND -- 4:Newbie issued y
2009-02-07 18:46:40 -- USERCOMMAND -- 1:Nugattz0r issued y
2009-02-07 18:46:54 -- USERCOMMAND -- 0:The Second issued y
2009-02-07 18:46:58 -- USERCOMMAND -- 2:Bomb issued preset
2009-02-07 18:47:00 -- INFO -- Python still alive
2009-02-07 18:47:09 -- USERCOMMAND -- 2:Bomb issued preset
2009-02-07 18:47:13 -- USERCOMMAND -- 5:WK|3|Mario@can issued y
2009-02-07 18:47:16 -- USERCOMMAND -- 1:Nugattz0r issued n
2009-02-07 18:47:18 -- USERCOMMAND -- 2:Bomb issued preset
2009-02-07 18:47:20 -- USERCOMMAND -- 7:[VOL]Swatek issued rank
2009-02-07 18:47:24 -- USERCOMMAND -- 2:Bomb issued rank
2009-02-07 18:47:25 -- USERCOMMAND -- 5:WK|3|Mario@can issued y
2009-02-07 18:47:25 -- USERCOMMAND -- 1:Nugattz0r issued toprank
2009-02-07 18:47:27 -- USERCOMMAND -- 5:WK|3|Mario@can issued y
2009-02-07 18:47:29 -- USERCOMMAND -- 5:WK|3|Mario@can issued y
2009-02-07 18:47:30 -- USERCOMMAND -- 2:Bomb issued toprank
2009-02-07 18:47:32 -- USERCOMMAND -- 4:{Q} Jage issued n
2009-02-07 18:47:39 -- USERCOMMAND -- 5:WK|3|Mario@can issued present
2009-02-07 18:47:39 -- ERROR -- ('Exception', '<no args>', ['  File "c:\Users\Karel Petr\xe1nek\Documents\Programovani\OpenLieroX\share\gamedir\scripts\dedicated_control_usercommands.py", line 339, in parseUserCommand\n    raise Exception, "Invalid user command"\n'])
2009-02-07 18:47:40 -- INFO -- Python still alive
2009-02-07 18:47:43 -- USERCOMMAND -- 0:The Second issued y
2009-02-07 18:47:47 -- USERCOMMAND -- 5:WK|3|Mario@can issued y
2009-02-07 18:47:51 -- USERCOMMAND -- 5:WK|3|Mario@can issued start'
2009-02-07 18:47:51 -- ERROR -- ('Exception', '<no args>', ['  File "c:\Users\Karel Petr\xe1nek\Documents\Programovani\OpenLieroX\share\gamedir\scripts\dedicated_control_usercommands.py", line 339, in parseUserCommand\n    raise Exception, "Invalid user command"\n'])
2009-02-07 18:47:52 -- USERCOMMAND -- 1:Nugattz0r issued start
2009-02-07 18:47:52 -- ERROR -- ('Exception', '<no args>', ['  File "c:\Users\Karel Petr\xe1nek\Documents\Programovani\OpenLieroX\share\gamedir\scripts\dedicated_control_usercommands.py", line 339, in parseUserCommand\n    raise Exception, "Invalid user command"\n'])
2009-02-07 18:47:52 -- USERCOMMAND -- 2:Bomb issued preset
2009-02-07 18:47:55 -- USERCOMMAND -- 7:[VOL]Swatek issued y
2009-02-07 18:48:07 -- USERCOMMAND -- 5:WK|3|Mario@can issued go
2009-02-07 18:48:07 -- ERROR -- ('Exception', '<no args>', ['  File "c:\Users\Karel Petr\xe1nek\Documents\Programovani\OpenLieroX\share\gamedir\scripts\dedicated_control_usercommands.py", line 339, in parseUserCommand\n    raise Exception, "Invalid user command"\n'])
2009-02-07 18:48:09 -- USERCOMMAND -- 2:Bomb issued start
2009-02-07 18:48:09 -- ERROR -- ('Exception', '<no args>', ['  File "c:\Users\Karel Petr\xe1nek\Documents\Programovani\OpenLieroX\share\gamedir\scripts\dedicated_control_usercommands.py", line 339, in parseUserCommand\n    raise Exception, "Invalid user command"\n'])
2009-02-07 18:48:20 -- INFO -- Python still alive
2009-02-07 18:48:27 -- ADMIN -- Worm 0 (Cee Dee) added to admins
2009-02-07 18:48:30 -- ADMIN -- 0:Cee Dee issued start
2009-02-07 18:48:36 -- ADMIN -- Worm 0 (Cee Dee) removed from admins
(...)
2009-02-07 18:52:35 -- USERCOMMAND -- 0:Bomb issued preset
2009-02-07 18:52:42 -- USERCOMMAND -- 0:Bomb issued preset
2009-02-07 18:52:58 -- USERCOMMAND -- 1:Police officer issued y
2009-02-07 18:53:00 -- USERCOMMAND -- 0:Bomb issued y
(...)
2009-02-07 19:12:07 -- USERCOMMAND -- 0:Cee Dee issued preset
2009-02-07 19:12:09 -- USERCOMMAND -- 0:Cee Dee issued y
2009-02-07 19:12:42 -- INFO -- Python still alive
2009-02-07 19:13:23 -- INFO -- Python still alive
2009-02-07 19:14:04 -- INFO -- Python still alive
2009-02-07 19:14:45 -- INFO -- Python still alive
2009-02-07 19:15:26 -- INFO -- Python still alive
2009-02-07 19:16:07 -- INFO -- Python still alive
2009-02-07 19:16:48 -- INFO -- Python still alive
2009-02-07 19:17:28 -- INFO -- Python still alive
2009-02-07 19:18:09 -- INFO -- Python still alive
2009-02-07 19:18:50 -- INFO -- Python still alive
2009-02-07 19:19:31 -- INFO -- Python still alive
2009-02-07 19:20:12 -- INFO -- Python still alive
2009-02-07 19:20:53 -- INFO -- Python still alive
2009-02-07 19:21:34 -- INFO -- Python still alive
2009-02-07 19:22:14 -- INFO -- Python still alive
2009-02-07 19:22:55 -- INFO -- Python still alive

**Comment by albertz** [comment]
Submitted by pelya

That's easy, I'll fix it

**Comment by albertz** [comment]
Submitted by pelya

Should be fixed in r.3272
