### ISSUE TITLE
fCurTime is too unaccurate with high values

### ISSUE THREAD

**Issue by albertz** [openlierox/openlierox#189]
Converted from [SourceForge issue 2680254](http://sourceforge.net/support/tracker.php?aid=2680254), submitted by albertzeyer

I already wrote that on mailing list:

After over 3 days of runtime, fCurTime becomes too big and thus to  
unexact as you can see here:

(gdb) frame 9
#9  0x0836b515 in PhysicsLX56::simulateProjectiles (this=0x8762ef8,

projs=@0xb4384268)
    at /home/az/Programmierung/openlierox/src/common/PhysicsLX56.cpp: 
909
909}
(gdb) next
Cannot find bounds of current function
(gdb) frame 8
#8  0x081ce6e5 in ~Ref (this=0xb4384218) at /home/az/Programmierung/

openlierox/include/Utils.h:117
117~Ref() { clear(); }
(gdb) finish
Run till exit from #8  0x081ce6e5 in ~Ref (this=0xb4384218)
    at /home/az/Programmierung/openlierox/include/Utils.h:117
PhysicsLX56::simulateProjectiles (this=0x8762ef8, projs=@0xb4384268)
    at /home/az/Programmierung/openlierox/src/common/PhysicsLX56.cpp: 
911
911cClient->fLastSimulationTime += orig_dt;
(gdb) print cClient->fLastSimulationTime
$1 = 293113.719
(gdb) step
912goto simulateProjectilesStart;
(gdb) print cClient->fLastSimulationTime
$2 = 293113.719
(gdb) print orig_dt
$3 = 0.00999999978
(gdb)
(gdb) bt
#0  PhysicsLX56::simulateProjectiles (this=0x8762ef8, projs=@0xb4384268)

```
at /home/az/Programmierung/openlierox/src/common/PhysicsLX56.cpp: 
```

912
#1  0x0821f479 in CClient::Simulation (this=0xa26ea008)

```
at /home/az/Programmierung/openlierox/src/client/CClient_Game.cpp: 
```

179
#2  0x0819f792 in CClient::Frame (this=0xa26ea008)

```
at /home/az/Programmierung/openlierox/src/client/CClient.cpp:1078
```
#3  0x08174d4c in GameLoopFrame () at /home/az/Programmierung/

openlierox/src/main.cpp:883
#4  0x08176827 in MainLoopThread () at /home/az/Programmierung/

openlierox/src/main.cpp:548
#5  0x0837aeaf in ThreadPool::start(int (_)(void_), void*, std::string

const&)::StaticAction::handle ()
#6  0x0837b590 in ThreadPool::threadWrapper (param=0x8502a28)

```
at /home/az/Programmierung/openlierox/src/common/ThreadPool.cpp:87
```
#7  0xb7f5db8b in ?? () from /usr/lib/libSDL-1.2.so.0
#8  0x08502a28 in ?? ()
#9  0x0837b458 in ?? ()
#10 0x08502ab8 in ?? ()
#11 0xb7f8bff4 in ?? () from /usr/lib/libSDL-1.2.so.0
#12 0x00000000 in ?? ()

The problem is, that for big float values, it could be that time + dt  
= time with a small dt > 0.

We could perhaps use a long or long long (to store milli or micro  
seconds) instead of a float. Then we would have always the same  
accurance no matter how high the value is.

**Comment by albertz** [comment]
Submitted by albertzeyer

We have an extra struct for time now: AbsTime and TimeDiff. Right now, they are using Uint64 but that is also easy to change now.

Anyway, this problem should be fixed now.
